stages:
  - test
  - build_and_release

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind

  before_script:
    - apk add --update build-base python3-dev py-pip
    - apk add libffi-dev libressl-dev musl-dev openssl-dev gcc libc-dev make
    - apk add cargo rust
    - pip install docker-compose

  script:
    - export
    - ln -s docker/environments/ci.env .env
    - docker-compose -f docker-compose.yml -f docker/compose/ci.yml up -d
    - docker-compose exec -T web pytest

  only:
    - develop
    - branches

docker_build_and_release:
  image: docker:latest
  stage: build_and_release
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
