x-hub20: &backend_service
  image: "hub20:${TAG-latest}"
  build:
    context: .
  restart: unless-stopped
  depends_on:
    redis:
      condition: service_healthy
    db:
      condition: service_healthy

services:
  db:
    image: "postgres:${HUB20_POSTGRES_SERVER_VERSION:-latest}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${HUB20_DATABASE_NAME:-hub20}"]
      interval: 5s
      retries: 5
    restart: unless-stopped

    # Make sure if to match the HUB20_DATABASE_* variables defined above
    environment:
      POSTGRES_DB: "${HUB20_DATABASE_NAME:-hub20}"
      POSTGRES_USER: "${HUB20_DATABASE_USER:-hub20}"
      POSTGRES_PASSWORD: "${HUB20_DATABASE_PASSWORD:-hub20_pass}"

  # Redis for cache, session engine, celery and channels transport
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: unless-stopped

  # services that run off the base image
  # Admin backend
  admin:
    <<: *backend_service
    environment:
      HUB20_URLCONF_MODULE: hub20.admin.urls

    command: >
      /bin/bash -c '
        django-admin collectstatic --noinput
        uvicorn hub20.api.asgi:application --port 80 --host 0.0.0.0
      '

  # Web API
  web:
    <<: *backend_service
    command: >
      /bin/bash -c '
        django-admin migrate;
        django-admin collectstatic --noinput
        uvicorn hub20.api.asgi:application --port 80 --host 0.0.0.0
      '

  # Celery app
  celery:
    <<: *backend_service
    command: celery -A hub20.api worker -l info -E

  # Celery beat (periodic tasks)
  celery_beat:
    <<: *backend_service
    command: celery -A hub20.api beat -l info -S django

  # Services to run background to listen and process different event streams
  process_stream_mined_blocks:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.blockchain.client.event_streams.process_mined_blocks

  process_stream_pending_transactions:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.blockchain.client.event_streams.process_pending_transactions

  process_stream_token_transfer_indexer:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.ethereum_money.client.event_streams.process_token_transfer_events

  process_stream_raiden_channel_event_indexer:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.raiden.client.event_streams.process_channel_events

  process_stream_raiden_channel_sync:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.raiden.client.node.sync_channels

  process_stream_raiden_payment_sync:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.raiden.client.node.sync_payments

  process_stream_open_route_transfers:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.core.integrations.web3.process_transfers_in_open_routes

  process_stream_pending_open_route_transfers:
    <<: *backend_service
    command: django-admin run_stream_processor hub20.apps.core.integrations.web3.process_pending_transfers_in_open_routes
