version: '3.4'

x-envvars: &ci_environment
  env_file:
    - ../environments/ci.env

services:
  db:
    <<: *ci_environment
    image: postgres

  redis:
    image: redis:latest

  web:
    <<: *ci_environment
    image: "hub20:${TAG:-latest}"
    command: >
      /bin/bash -c "
        while ! nc -w 1 -z db 5432; do sleep 0.5; done;
        django-admin migrate;
        django-admin collectstatic --noinput
        uvicorn hub20.api.asgi:application --port 80 --host 0.0.0.0 --root-path="/api" --reload --reload-dir /app/hub20
      "
    build:
      context: ../../
    depends_on:
      - db
      - redis
